
package:
  name: pyglet1.2
  version: 1.2.4

source:
  hg_url: https://bitbucket.org/pyglet/pyglet
  hg_tag: pyglet-1.2.4

build:
    number: 1
    script: python setup.py install

requirements:
    build:
        - python

    run:
        - python

test:
    imports:
        - pyglet
    # commands:
    #     - tests/test.py

about:
  home: https://bitbucket.org/pyglet/pyglet/wiki/Home
  license: BSD
